namespace AdventOfCode2022.Days
{
    static class Day2
    {
        public static void Solve()
        {
            Console.WriteLine($"Day 2, part 1: " + Part1(FullInput));
            Console.WriteLine($"Day 2, part 2: " + Part2(FullInput));
            Console.WriteLine();
        }

        public static int Part1(string input)
        {
            return input.Split(Environment.NewLine)
                    .Select(x => x.Trim())
                    .Where(x => !string.IsNullOrEmpty(x))
                    .Select(InputToShape)
                    .Select(GetScore)
                    .Sum();

            (Shape, Shape) InputToShape(string input)
            {
                var moves = input.Split(" ").Select(x => x[0]).ToArray();
                return (MoveToShape(moves[0]), MoveToShape(moves[1]));
            }
            int GetScore((Shape, Shape) round)
                => round switch
                {
                    (Shape.Rock, Shape.Rock) => 4,
                    (Shape.Rock, Shape.Paper) => 8,
                    (Shape.Rock, Shape.Scissors) => 3,
                    (Shape.Paper, Shape.Rock) => 1,
                    (Shape.Paper, Shape.Paper) => 5,
                    (Shape.Paper, Shape.Scissors) => 9,
                    (Shape.Scissors, Shape.Rock) => 7,
                    (Shape.Scissors, Shape.Paper) => 2,
                    (Shape.Scissors, Shape.Scissors) => 6,
                    _ => throw new Exception($"Unknown round: {round}")
                };
            Shape MoveToShape(char move)
                => move switch
                {
                    'A' or 'X' => Shape.Rock,
                    'B' or 'Y' => Shape.Paper,
                    'C' or 'Z' => Shape.Scissors,
                    _ => throw new Exception($"Unknown move: {move}")
                };
        }

        public static int Part2(string input)
        {
            return input.Split(Environment.NewLine)
                        .Select(x => x.Trim())
                        .Where(x => !string.IsNullOrEmpty(x))
                        .Select(InputToShapeAndResult)
                        .Select(GetScore)
                        .Sum();

            (Shape, Result) InputToShapeAndResult(string input)
            {
                var moves = input.Split(" ").Select(x => x[0]).ToArray();
                return (ConvertToShape(moves[0]), ConvertToResult(moves[1]));
            }
            int GetScore((Shape, Result) round)
                => round switch
                {
                    (Shape.Rock, Result.Loss) => 3, // loss + scissors
                    (Shape.Rock, Result.Draw) => 4, // draw + rock
                    (Shape.Rock, Result.Win) => 8, // win + paper
                    (Shape.Paper, Result.Loss) => 1, // loss + rock
                    (Shape.Paper, Result.Draw) => 5, // draw + paper
                    (Shape.Paper, Result.Win) => 9, // win + scissors
                    (Shape.Scissors, Result.Loss) => 2, // loss + paper
                    (Shape.Scissors, Result.Draw) => 6, // draw + scissors
                    (Shape.Scissors, Result.Win) => 7, // win + rock
                    _ => throw new Exception($"Unknown round: {round}")
                };
            Shape ConvertToShape(char move)
                => move switch
                {
                    'A' => Shape.Rock,
                    'B' => Shape.Paper,
                    'C' => Shape.Scissors,
                    _ => throw new Exception($"Unknown move: {move}")
                };
            Result ConvertToResult(char result)
                => result switch
                {
                    'X' => Result.Loss,
                    'Y' => Result.Draw,
                    'Z' => Result.Win,
                    _ => throw new Exception($"Unknown result: {result}")
                };
        }

        private enum Shape
        {
            Rock,
            Paper,
            Scissors
        }

        private enum Result
        {
            Loss,
            Draw,
            Win
        }

        #region Input

        private const string SmallInput = @"
            A Y
            B X
            C Z";

        private const string FullInput = @"
            A Y
            B X
            C X
            A Z
            B Y
            C X
            C X
            C X
            C X
            C X
            A Z
            B Y
            C X
            A Z
            A Z
            B Y
            A Z
            B X
            C Z
            C X
            C X
            B Y
            C X
            A X
            B Y
            B Z
            A Z
            B Y
            C X
            C X
            C X
            A Z
            B Y
            C X
            A Z
            C X
            B Y
            C X
            C X
            B Y
            A Z
            A Z
            C X
            C X
            A Y
            B X
            C X
            B X
            C X
            C X
            A Z
            C Z
            C X
            A Y
            B Y
            B Y
            B X
            C X
            C X
            C X
            A Y
            A Z
            C X
            A Z
            C X
            B Y
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            C X
            C X
            B Y
            C X
            B Y
            A X
            A Y
            C Y
            A Z
            C X
            C X
            A X
            A Z
            A X
            C X
            C X
            A X
            C X
            B Y
            A Z
            A Y
            A Z
            B X
            C X
            B X
            C X
            C X
            A Z
            C X
            C Z
            C X
            C X
            C X
            C X
            C X
            A Z
            A X
            C X
            A Z
            C X
            C X
            A Z
            C X
            A Z
            A Y
            C X
            C X
            A Z
            A Z
            C X
            C X
            A Z
            A Z
            C Z
            C X
            A Z
            A Z
            C X
            B Y
            C X
            C X
            A Y
            A Z
            A Z
            A Z
            A Y
            B Y
            A Z
            C X
            A Y
            A Z
            A Y
            A Z
            C X
            C X
            C X
            B X
            B Y
            A Z
            A Z
            A Z
            C X
            A Z
            A X
            B X
            C X
            C X
            C X
            A Z
            A Z
            A Z
            C X
            C X
            A X
            A Z
            C Y
            A Z
            C X
            C X
            C Z
            C X
            A Z
            A X
            C Y
            A X
            C X
            C X
            C X
            A X
            A X
            C X
            A Z
            A Z
            A Z
            A Z
            A Z
            A Y
            C X
            A Z
            A Z
            A Z
            B Y
            C X
            C X
            A X
            B X
            A Z
            C X
            A Z
            C X
            A Z
            C X
            A Z
            A Y
            C X
            C X
            C X
            A Y
            C X
            C Y
            C Z
            C X
            C X
            B Y
            C X
            A Z
            C Z
            A Z
            C X
            A Y
            B Y
            C X
            C X
            C X
            B X
            A Z
            C X
            C X
            C X
            B X
            A Z
            A Z
            C X
            C X
            C X
            A Z
            A X
            B Y
            C Y
            C X
            A Z
            A Z
            A Z
            B Y
            B X
            C X
            A Z
            A Y
            B Z
            C X
            C X
            A Z
            A X
            C X
            A Z
            B Y
            A Z
            C Z
            B X
            A Z
            C X
            C X
            C X
            A Y
            C X
            C X
            A Z
            A X
            C Z
            A Y
            C X
            C X
            A Y
            A X
            B Y
            C X
            C X
            C X
            A Z
            A X
            C X
            A X
            A X
            C X
            C X
            A Z
            C X
            A Z
            A X
            A Z
            C X
            B Y
            A Z
            C X
            A Z
            A X
            B X
            C X
            B Y
            A Y
            A Y
            C Z
            B Z
            C X
            C X
            C X
            A Z
            C Z
            A Y
            C X
            A Y
            C Z
            A Y
            B Y
            C X
            C X
            A Z
            B Y
            C X
            A Z
            C X
            C X
            A Z
            B Y
            C X
            B Y
            C X
            B Y
            A Y
            C X
            A X
            A X
            B X
            C X
            A Z
            C X
            B Y
            A Y
            C X
            B Y
            B X
            C X
            C X
            A Z
            B X
            A X
            C X
            C X
            B Y
            C Z
            B X
            C X
            A Z
            A Z
            A X
            C X
            A Z
            C X
            A Z
            C X
            A Z
            C X
            A Z
            A Y
            A Y
            C Z
            C X
            A X
            C X
            A Z
            C X
            B X
            A Z
            A Y
            A Z
            C X
            A Z
            C X
            B Y
            A X
            C X
            A Y
            C X
            C X
            C X
            A Z
            A Y
            C X
            A X
            C X
            A Z
            C X
            C X
            A Y
            C X
            C X
            C X
            A Z
            A Z
            C X
            A Z
            B X
            A Z
            C X
            B Y
            B X
            C X
            B Y
            A Z
            A X
            C X
            A Y
            A X
            A Z
            B Y
            A X
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            A X
            A Z
            A Z
            B Y
            A Z
            A X
            A Z
            C X
            B X
            A Y
            A X
            A Y
            C X
            A Z
            C X
            A Z
            B X
            A Y
            C X
            C X
            A Z
            A Z
            C X
            C Y
            A Z
            A Z
            A Z
            A Y
            C X
            C X
            A Z
            A Z
            A Z
            B Y
            C X
            A Z
            C X
            A Y
            A Z
            A Z
            A Z
            C X
            A X
            A Z
            A Z
            B Y
            B X
            A Z
            A X
            C X
            C X
            A Z
            A Z
            C X
            A X
            A Z
            C X
            A X
            C X
            A Z
            A Y
            C X
            B Y
            B Y
            C X
            C X
            C X
            C X
            C X
            A X
            A X
            A Y
            A Z
            A X
            C X
            A X
            A Z
            B Y
            A X
            A X
            C X
            A Z
            C X
            C X
            C X
            A Z
            A X
            A X
            C X
            C X
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            C Z
            C X
            A Z
            A Z
            C X
            C X
            A Z
            A Z
            C X
            A Z
            A Z
            A Z
            A Z
            C X
            A X
            C X
            B Y
            C X
            A X
            A X
            A Y
            C X
            A Y
            A Z
            C X
            C X
            C Z
            C X
            C X
            C X
            B X
            C X
            C X
            C X
            A Y
            C X
            C X
            A Z
            C X
            A Y
            C X
            C Z
            C X
            C X
            B X
            A Z
            C X
            C X
            C X
            C X
            C X
            B X
            A Z
            C X
            A Z
            B X
            B Y
            B Y
            C X
            C X
            C Y
            A Z
            C X
            C X
            A X
            A X
            A X
            A X
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            A X
            C X
            C X
            B Y
            B Y
            A Z
            C X
            A X
            A Z
            A Z
            B Y
            C X
            C X
            A Z
            C X
            A Z
            C X
            B X
            C X
            A Y
            C X
            C X
            A X
            B Y
            B Y
            C Z
            C X
            C X
            B Y
            A X
            C X
            C X
            A X
            A Z
            C X
            C X
            A Z
            B Y
            A Z
            C X
            C X
            A X
            A X
            C X
            C Z
            C X
            A Z
            B X
            C X
            B Y
            A Y
            B X
            A Z
            A Z
            A X
            A Z
            A Y
            A Z
            A X
            A Z
            C X
            C X
            A Z
            B Y
            A Z
            B X
            B Y
            A Z
            C X
            C Y
            A Z
            C X
            C X
            A X
            A Z
            A X
            C X
            C X
            A Z
            C X
            C X
            C X
            C X
            A X
            B X
            A Z
            A Z
            C X
            A X
            A X
            C X
            C X
            A Z
            A Z
            C X
            C X
            A X
            A Z
            C X
            A X
            A Z
            A Z
            C X
            A Z
            A Z
            C X
            C X
            A Z
            C X
            C X
            A Z
            C X
            C X
            A Z
            A X
            C X
            C X
            A Z
            A Z
            C X
            C X
            C X
            A Y
            C X
            C X
            B Y
            C X
            C X
            C X
            C X
            A Z
            A Z
            A X
            C X
            A X
            C X
            A Z
            B X
            A Z
            C X
            C X
            A Z
            A Y
            C X
            C X
            A Z
            C X
            B X
            B X
            B Y
            A Y
            A Y
            A Z
            A Z
            A Z
            C X
            C X
            A Z
            C X
            B Y
            C X
            B Z
            A Z
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            B X
            A Y
            C X
            A X
            A Z
            B Y
            A X
            C X
            C X
            C X
            C X
            C X
            A Z
            A X
            A Z
            A X
            A Z
            A Z
            C X
            A X
            C X
            B X
            C Z
            A X
            B X
            A Y
            C X
            A Z
            A Z
            B X
            B Y
            B Y
            C X
            A Z
            A X
            C X
            C X
            B Z
            B X
            B Y
            A Z
            B Y
            A Z
            C X
            A Z
            A X
            A Z
            C X
            C X
            C X
            A X
            C X
            A Z
            C X
            C X
            C Y
            B X
            C X
            A X
            C X
            A X
            A Z
            C Z
            A Z
            C X
            A Y
            C X
            C X
            B Y
            C X
            C X
            A Z
            C X
            C X
            C X
            A Z
            C Y
            C X
            A X
            A Z
            A X
            C X
            A Z
            A Z
            B Y
            B X
            A Z
            C X
            A Z
            C X
            A X
            C X
            C Y
            A Z
            A Y
            C Z
            C X
            C Z
            A Z
            A Z
            C X
            C X
            A Y
            A X
            B Y
            C X
            A Y
            C X
            A Y
            C X
            A Z
            B X
            A Y
            C X
            B X
            A Z
            C X
            A Z
            A Z
            A Y
            A Z
            A X
            B Y
            C X
            C X
            C X
            A Z
            A X
            C X
            A Y
            A Y
            C X
            A Z
            C X
            C Y
            C X
            C X
            A X
            A Z
            A X
            A X
            C X
            A X
            A Z
            C X
            A Y
            A Y
            C X
            B Y
            A Y
            C X
            A Z
            A Z
            A X
            C X
            A Y
            C X
            C X
            C X
            C X
            A Y
            A Z
            B Y
            A X
            A Y
            C X
            C X
            C X
            B X
            A Z
            C X
            C X
            B X
            A Z
            A X
            C X
            A X
            C X
            B Y
            A Z
            C X
            C X
            B X
            A Z
            A Z
            A Z
            C X
            C X
            C X
            C Y
            C X
            C X
            A Z
            C X
            A Z
            C X
            C X
            B X
            A X
            A Z
            C X
            B Z
            C X
            C X
            A X
            A Y
            C X
            A Z
            A Z
            C X
            C X
            C X
            C X
            C X
            C X
            B Y
            A Z
            C X
            A X
            A Z
            A Z
            C X
            C X
            C X
            A Z
            C X
            B Y
            A Z
            A Z
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            A Y
            A X
            C X
            A Z
            C X
            C X
            A Z
            A Z
            A X
            A Z
            C X
            A Z
            A X
            A Z
            C X
            C X
            C Z
            A X
            C X
            C X
            A X
            A X
            C X
            A Z
            A Z
            A Z
            C X
            C X
            A Z
            B Z
            A Z
            A Z
            C X
            A Z
            C X
            A Z
            B X
            C X
            A Z
            B Y
            B Y
            C X
            A X
            A Z
            C X
            C X
            A Z
            C Y
            B Y
            A Z
            C X
            C X
            A Z
            A Z
            C Z
            A Z
            C X
            C X
            A Y
            C X
            A Y
            B X
            C Z
            C X
            A Y
            C X
            B Y
            C X
            C X
            C Z
            A Z
            A Z
            C X
            C X
            A Z
            B Z
            C X
            A Z
            C X
            A Z
            C X
            C X
            C Y
            C X
            B Y
            A X
            A Z
            C X
            B Y
            A Z
            B Y
            C X
            C Y
            C Z
            A X
            A Z
            A X
            C X
            C X
            A Z
            A Z
            C X
            C X
            C X
            C X
            B Y
            B Y
            A Y
            C X
            C X
            C X
            A X
            C X
            B Y
            A Z
            B Y
            C X
            C X
            B Y
            C X
            B Y
            C X
            C X
            C X
            A Z
            A Z
            C X
            C X
            B Z
            A X
            C X
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            C X
            A Y
            A Z
            C X
            A Z
            A Y
            C X
            A X
            C Y
            A Y
            A Y
            C X
            C X
            A X
            A Y
            C X
            B Y
            A Z
            B Y
            C X
            B X
            C X
            C X
            C X
            B Z
            A Y
            C X
            B Y
            C X
            A X
            C X
            C X
            B X
            A Z
            C X
            A Z
            C X
            C X
            C X
            C X
            C X
            C X
            A X
            A Z
            A Z
            C X
            C X
            C Z
            B X
            C Z
            C X
            B X
            C X
            A Z
            B Y
            A Z
            C Z
            C X
            B X
            A X
            A Z
            C X
            C X
            A Z
            A Z
            A Z
            A X
            C X
            C X
            A Y
            A Z
            C X
            A Z
            B Y
            C X
            C Z
            A Z
            C X
            C X
            C X
            A X
            A Z
            A Z
            C X
            A Y
            A Y
            C X
            C X
            C X
            C X
            C X
            A Z
            C X
            B X
            C X
            B X
            B Y
            A Z
            C X
            B Y
            A Y
            C Z
            A Z
            A X
            C X
            A Z
            C X
            A Z
            C Z
            C X
            C X
            A Z
            C X
            C X
            C X
            B Y
            A Z
            B X
            A Z
            A Z
            B X
            A X
            A Z
            C X
            C X
            A Y
            C X
            A Z
            B Y
            C Y
            A Z
            C Y
            C X
            A Z
            C X
            C X
            A X
            C X
            A X
            A Z
            B Y
            B Y
            C X
            B Y
            C Z
            C X
            C X
            B Y
            A Z
            C X
            C X
            C X
            C X
            C X
            A X
            A Z
            B Y
            A Y
            C X
            C X
            C Z
            C X
            A X
            C X
            A Z
            B Y
            A Z
            B X
            C X
            C X
            A Z
            C X
            A Y
            A Y
            C X
            B X
            C X
            B X
            A Y
            A Z
            A Z
            C X
            A Z
            A X
            A Z
            C X
            C X
            C X
            A Z
            B X
            B X
            A Z
            C X
            B Y
            C X
            C X
            A Z
            A X
            C X
            B Y
            C X
            C X
            C X
            A X
            A X
            B Y
            A Y
            A X
            C X
            A Z
            B X
            A Z
            B Y
            C X
            B Y
            A Y
            C X
            C X
            C X
            A Y
            A Z
            A Z
            A X
            A Z
            A X
            C X
            A Z
            A Y
            A Z
            A Z
            A Z
            A X
            A Z
            A Z
            C X
            C X
            C X
            A Z
            C X
            C X
            B Y
            C X
            C X
            C X
            C Y
            A Z
            A Z
            A Z
            C X
            A Z
            B X
            A X
            A Z
            A Y
            C X
            A Z
            C X
            A Z
            A Y
            B Y
            C X
            A X
            A Z
            A Z
            C Y
            A X
            B Y
            B Y
            C X
            A Z
            A Z
            A Z
            A Z
            A Z
            A Z
            A Z
            C X
            C X
            B Y
            C X
            C X
            A Y
            C X
            A Z
            C X
            A X
            C X
            A X
            C X
            C X
            B X
            C X
            B X
            C X
            C X
            A Y
            A X
            A Z
            C X
            A X
            A Y
            A Z
            C X
            C X
            C X
            B Y
            A Z
            A Y
            A Z
            C X
            A Y
            B X
            C X
            A X
            A Y
            A Y
            A Z
            A Z
            A Z
            C X
            A Z
            A X
            A Z
            C X
            B X
            A Z
            C X
            C X
            A X
            A Z
            A Z
            B Y
            A Z
            A X
            A Z
            A Z
            A Z
            A X
            B Y
            A X
            A Z
            C X
            B X
            A Z
            A Z
            A Y
            B Y
            A Y
            B Y
            C X
            C X
            A Z
            B Y
            A Z
            A X
            A Z
            A Z
            C X
            C X
            A Z
            A X
            C X
            B Y
            C X
            C X
            C X
            C Z
            A Y
            C X
            A Y
            A Y
            A Y
            A Z
            A X
            A Z
            A X
            A Z
            B Y
            C X
            A Z
            A Y
            C X
            B Y
            A Z
            B Y
            C X
            B X
            B Y
            C X
            A Z
            B X
            C X
            B Y
            B Y
            C X
            C X
            A Z
            B X
            A X
            A Z
            C X
            A Z
            C X
            C X
            A Z
            B X
            A Z
            C Y
            C X
            A Z
            A X
            B Y
            B Y
            C Y
            B Y
            A Y
            C X
            A X
            C X
            C X
            C X
            A Y
            A Z
            B Y
            A Z
            A Y
            C X
            A Y
            A Y
            A Y
            C X
            B X
            B X
            C X
            B X
            C X
            C X
            A X
            A X
            A X
            C X
            C X
            C Y
            A Y
            A Z
            C X
            B Y
            C X
            A X
            C X
            A Z
            C X
            C X
            C X
            B X
            C X
            C Z
            A Z
            C Y
            B Y
            A Y
            A Z
            A Z
            A X
            A Y
            C X
            C Y
            C X
            C X
            A X
            A Y
            A Z
            C X
            B X
            B Y
            B Y
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            B Y
            C X
            C X
            A Z
            A Z
            A Z
            A X
            A Y
            A Z
            C Z
            A Z
            C X
            C X
            B Y
            A X
            C X
            A Z
            C X
            A X
            C X
            A Z
            C X
            C X
            A Z
            A X
            C X
            C X
            C X
            A Y
            C X
            C X
            A Z
            C X
            A Z
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            C X
            A Z
            A Z
            B Z
            A Z
            A Y
            C X
            B X
            C X
            C X
            C Z
            C X
            C X
            C X
            A X
            A Z
            A Z
            A Z
            C X
            C X
            C X
            A Z
            B Y
            C X
            C X
            C X
            A Z
            C X
            A Y
            C X
            B Y
            A Z
            C X
            B X
            C X
            A X
            C X
            C X
            C X
            A Z
            A Z
            A Z
            B Z
            C X
            A Z
            A X
            C X
            B X
            A X
            A Y
            B Y
            B Y
            A Z
            C X
            C X
            C X
            C X
            A Z
            A Z
            C X
            A X
            B Y
            B Y
            A Z
            A Z
            C X
            C X
            A Z
            A Y
            C X
            A Y
            A Z
            A Y
            C X
            A Z
            C X
            A Z
            B Y
            A X
            A Z
            C X
            A X
            C X
            A Z
            C X
            C X
            A Z
            B X
            B X
            A Z
            C X
            A Y
            A Z
            C X
            A X
            A X
            A Z
            A Y
            C X
            A Z
            B Z
            C X
            A Z
            C X
            A Z
            A Z
            C X
            A Z
            B X
            A Z
            C X
            A Z
            A Z
            C X
            C X
            A X
            A Z
            A Z
            C X
            A Z
            C X
            A Z
            C X
            A X
            A Z
            A Z
            C Z
            C X
            C X
            B Y
            B Y
            C X
            C X
            C X
            B X
            A X
            C X
            A X
            B Y
            C X
            B Y
            A Z
            A Z
            A Y
            A Z
            B X
            A X
            C X
            B Y
            C X
            A Z
            C X
            C X
            A Z
            A X
            C X
            C X
            A Z
            B Y
            C X
            A Z
            B Y
            A Z
            A Z
            A X
            C X
            A Z
            C X
            B Y
            C X
            C X
            C X
            A X
            B Y
            C X
            A X
            C X
            A Z
            C X
            C X
            B X
            B X
            C X
            C X
            A Z
            B X
            C X
            A X
            C X
            B Y
            A Y
            C Z
            C X
            A Z
            C Z
            B Y
            B Y
            A Z
            C Z
            C X
            C X
            C X
            A X
            C X
            A Z
            B X
            A Z
            B Y
            A Z
            B X
            A X
            A Z
            A Z
            C X
            B X
            C X
            A Z
            B Y
            A Z
            C X
            A Z
            A Z
            A X
            A Z
            A X
            A X
            C X
            B X
            C X
            C X
            B Y
            C X
            C X
            A X
            C X
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            A Z
            A Z
            B Y
            C X
            C Z
            C X
            B Y
            C X
            C X
            C X
            A Z
            A Y
            A X
            C X
            C X
            B Y
            C Z
            C X
            A Y
            B Y
            C X
            C X
            A Z
            A Z
            C X
            C X
            C X
            B X
            C X
            C X
            C X
            C X
            B Y
            A X
            C X
            C X
            A Z
            C X
            C X
            C X
            A Z
            C X
            C X
            B Y
            C X
            A Y
            C X
            A Z
            A Z
            B Y
            C X
            C Y
            A Y
            C X
            B Y
            A Z
            B X
            C X
            C X
            A X
            C X
            C X
            C X
            C X
            A X
            A X
            A Z
            C X
            B Z
            C X
            A Y
            A Z
            A Z
            C X
            C X
            C X
            A Z
            A Z
            A X
            A Z
            A Z
            A Z
            A Y
            A X
            A Z
            C X
            B Y
            C X
            A Z
            C X
            C Z
            B X
            C X
            C X
            A Z
            A X
            B X
            C X
            A Z
            A Z
            A Z
            C Z
            C X
            B Y
            C X
            C X
            C X
            A Z
            B Y
            C X
            C X
            C X
            C X
            C X
            C X
            A X
            C Z
            B Y
            A X
            A X
            B X
            C X
            C X
            C X
            A Z
            A Z
            B X
            C X
            C X
            A Z
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            C Y
            C X
            C X
            A Z
            A Z
            A Z
            A Y
            A X
            A X
            C X
            A Z
            B X
            A Z
            C X
            B X
            C X
            A Y
            A X
            C X
            C X
            C X
            B X
            B X
            C X
            A Z
            A Z
            C X
            C X
            A Z
            B X
            A Z
            A Y
            A X
            A Y
            C X
            A Z
            B Y
            C X
            A Z
            C X
            C X
            A Z
            A Z
            A Y
            B X
            A Z
            C X
            A X
            A Z
            A Z
            A Z
            A X
            C X
            A Z
            A Z
            B X
            A Y
            C X
            C X
            C X
            C X
            B X
            B Y
            C X
            A Z
            C X
            B Y
            B Y
            C X
            B X
            A Z
            C X
            C X
            A Z
            B Y
            C X
            A Z
            C X
            C X
            A Z
            C X
            A Z
            A X
            C X
            C X
            A X
            A Z
            C X
            A X
            C X
            C X
            A X
            C X
            A X
            A Y
            A Z
            A Y
            A Z
            C X
            A Z
            A Z
            B Z
            A Y
            A Z
            C X
            A Z
            C X
            A X
            C X
            C Y
            C X
            C X
            C X
            A Z
            B X
            C X
            C X
            A Z
            A Z
            C Z
            C X
            A X
            A Y
            B Y
            A Z
            A X
            B X
            C X
            C X
            C X
            A Y
            C X
            A Z
            C X
            C X
            A Z
            A X
            C X
            C Z
            C X
            C X
            C X
            A Z
            A Y
            C X
            C X
            A Z
            C X
            C Y
            C X
            C X
            A Z
            A X
            C X
            B X
            A Z
            A Z
            C X
            A Z
            A Z
            C X
            A Y
            C Y
            A Z
            A Z
            B X
            C X
            A Z
            A Z
            C X
            C X
            C X
            B Y
            A Z
            B Y
            C X
            B X
            A X
            C X
            A Z
            A Y
            C X
            A Z
            C Z
            A X
            C X
            A Z
            C X
            C X
            A Z
            C X
            A Y
            C X
            C X
            A Y
            C X
            B X
            C X
            C X
            B Y
            A X
            C X
            A Y
            B Y
            C X
            A X
            A Z
            C Z
            A X
            C X
            C X
            B X
            A Z
            B Z
            A Z
            A X
            A Y
            C X
            A X
            B X
            C X
            C X
            C X
            C X
            A Z
            C X
            A Z
            A Z
            C X
            B X
            C X
            A Y
            A Z
            A X
            A X
            C X
            A Y
            C X
            C X
            A Y
            C X
            B X
            A Z
            C X
            A Z
            B X
            A Z
            B Y
            C X
            C X
            C X
            A Z
            C X
            C X
            A X
            C X
            A Z
            C X
            C X
            A Z
            C X
            A X
            B Y
            A Y
            C X
            C X
            C X
            A X
            C X
            A Z
            C X
            A X
            C X
            C X
            A Y
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            A Y
            A Z
            C X
            C X
            C X
            A Z
            A Z
            C Z
            A Y
            C X
            C X
            B Z
            B Y
            B Y
            B Y
            C Z
            B Y
            A Z
            B X
            C X
            A Z
            A Y
            C X
            B Y
            C X
            A X
            B X
            A Z
            A Z
            C X
            C Y
            A Z
            B Y
            A Z
            A Z
            C X
            C X
            B Y
            C X
            A Z
            C Z
            A X
            C X
            C X
            C X
            A Z
            C X
            B X
            B Y
            C X
            A Z
            A Z
            C X
            A Z
            C Z
            C X
            B X
            A X
            B Z
            A Z
            C X
            A X
            C X
            C X
            C X
            C X
            A Z
            C X
            C X
            C X
            C X
            A Z
            A Z
            C X
            C X
            A X
            A Z
            C X
            A X
            C X
            C Y
            C X
            A Z
            B X
            A Y
            A Z
            C Y
            A Z
            C X
            A Y
            C X
            A X
            C X
            A X
            C X
            A Z
            C X
            A X
            A Z
            A X
            A Y
            C Z
            C X
            A X
            A Z
            A Z
            A Z
            A Z
            C X
            C X
            C Z
            A X
            A Z
            B Y
            A Z
            A Z
            B X
            B Y
            A X
            A Y
            A Z
            C X
            A Z
            C X
            A Z
            B X
            B X
            C X
            C X
            C X
            A X
            C X
            A Z
            B X
            A Y
            B X
            C X
            A X
            C X
            A X
            A Z
            A Z
            A Z
            C X
            B Y
            C X
            B Y
            C X
            A Z
            A Z
            A Z
            C X
            C X
            B Y
            A Y
            C Y
            A Z
            C X
            C X
            A Z
            C X
            A Z
            C Z
            B X
            C X
            C X
            A Z
            B Y
            A Y
            C X
            A X
            ";

        #endregion
    }
}
